const  os= require('os')
const path = require('path')
const math=require('./math')
console.log(__dirname)
console.log(__filename)
console.log("-------------")
console.log(path.dirname(__filename))
console.log(path.basename(__filename))
console.log(path.extname(__filename))
console.log(path.parse(__filename))
console.log('-----------------------------------------------------')
console.log(math.add(3,4))